// PRACTICAS/examenvueFMB/src/components/RegisterComponent.vue
<template>
    <form class="m-5" @submit.prevent="register">
        <label>Email</label>
        <input
            type="email"
            class="form-control"
            name="cajaEmail"
            required
            v-model="data.email"
        /><br />
        <label>Nombre</label>
        <input
            type="text"
            class="form-control"
            name="cajaNombre"
            required
            v-model="data.nombre"
        /><br />
        <label>Contraseña</label>
        <input
            type="password"
            class="form-control"
            name="cajaPass"
            v-model="data.pass"
            required
        /><br />
        <button type="submit" class="btn btn-info">Login</button>
    </form>
</template>

<script setup>
import { reactive, onMounted } from "vue";
import { useRouter } from "vue-router";
import authService from "@/services/authService";

const router = useRouter();

const data = reactive({
    nombre: "",
    email: "",
    pass: "",
});

const register = () => {
    if (data.email && data.pass && data.nombre) {
        const newUser = {
            idUsuario: 0,
            nombre: data.nombre,
            email: data.email,
            pass: data.pass,
        };

        authService.register(newUser).then(() => {
            router.push("/login");
        });
    }
};

onMounted(() => {
    authService.checkUser().then((user) => {
        if (user) {
            router.push("/perfil");
        }
    });
});
</script>

// PRACTICAS/examenangularFMB/src/app/components/register/register.component.ts
// Base
import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';
// Models
import { User } from 'src/app/models/user';
// Service
import { AuthServiceService } from 'src/app/services/auth-service.service';
// Rutas
import { ActivatedRoute, ParamMap, Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent implements OnInit {
  // Form inputs
  @ViewChild('cajaNombre') cajaNombre!: ElementRef;
  @ViewChild('cajaEmail') cajaEmail!: ElementRef;
  @ViewChild('cajaPass') cajaPass!: ElementRef;

  constructor(
    private authService: AuthServiceService,
    private router: Router
  ) {}

  login(): void {
    const nombre = this.cajaNombre.nativeElement.value;
    const email = this.cajaEmail.nativeElement.value;
    const pass = this.cajaPass.nativeElement.value;

    if (email && pass && nombre) {
      const newUser = new User(0, nombre, email, pass);

      this.authService.register(newUser).then(() => {
        this.router.navigate(['/login']);
      });
    }
  }

  ngOnInit(): void {
    this.authService.checkUser().then((user) => {
      if (user) {
        this.router.navigate(['/perfil']);
      }
    });
  }
}

<form class="m-5">
  <label>Email</label>
  <input
    type="email"
    class="form-control"
    name="cajaEmail"
    required
    #cajaEmail
  /><br />
  <label>Nombre</label>
  <input
    type="text"
    class="form-control"
    name="cajaNombre"
    required
    #cajaNombre
  /><br />
  <label>Contraseña</label>
  <input
    type="password"
    class="form-control"
    name="cajaPass"
    #cajaPass
    required
	
  /><br />
  <button type="submit" class="btn btn-info" (click)="login()">Login</button>
</form>
