// react/routercollatz/src/components/Collatz.jsx
import React, { Component } from "react";

export default class Collatz extends Component {
    /*
		Si el número es par, se divide entre 2.
		Si el número es impar, se multiplica por 3 y se suma 1.
	*/

    state = {
        resultados: [],
        operaciones: [],
    };

    calcularCollatz = (num) => {
        let resultado = num;

        if (resultado === 1) {
            return;
        }

        if (num % 2 === 0) {
            resultado = num / 2;
            this.state.resultados.push(resultado);
            this.state.operaciones.push(`${num} / 2`);
            this.calcularCollatz(resultado);
        } else {
            resultado = resultado * 3 + 1;
            this.state.resultados.push(resultado);
            this.state.operaciones.push(`${num} * 3 + 1`);
            this.calcularCollatz(resultado);
        }

        this.setState({
            resultados: this.state.resultados,
        });

        return;
    };

    resetStates = () => {
        this.state.resultados.splice(0);
        this.state.operaciones.splice(0);
        this.setState({
            resultados: this.state.resultados,
            operaciones: this.state.operaciones,
        });
    };

    componentDidMount() {
        this.resetStates();
        this.calcularCollatz(parseInt(this.props.num));
    }

    componentDidUpdate(oldProps) {
        if (oldProps.num !== this.props.num) {
            this.resetStates();
            this.calcularCollatz(parseInt(this.props.num));
        }
    }

    render() {
        return (
            <div>
                <h1 className="App-header">Collatz: {this.props.num}</h1>
                <table
                    className={
                        this.props.theme === "dark"
                            ? "table table-dark"
                            : "table"
                    }
                >
                    <thead>
                        <tr>
                            <th>Operación</th>
                            <th>Resultado</th>
                        </tr>
                    </thead>
                    <tbody>
                        {this.state.resultados.map((resultado, index) => {
                            return (
                                <tr key={index}>
                                    <td>{this.state.operaciones[index]}</td>
                                    <td>{resultado}</td>
                                </tr>
                            );
                        })}
                    </tbody>
                </table>
            </div>
        );
    }
}

// angular/angularcollatz/src/app/components/collatz/collatz.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, ParamMap, Router } from '@angular/router';

@Component({
  selector: 'app-collatz',
  templateUrl: './collatz.component.html',
  styleUrls: ['./collatz.component.css'],
})
export class CollatzComponent implements OnInit {
  public numCollatz!: number;
  public resultadoCollatz: Array<number>;

  constructor(private route: ActivatedRoute) {
    this.resultadoCollatz = [];
  }

  // Si el número es par, se divide entre 2.
  // Si el número es impar, se multiplica por 3 y se suma 1.
  calcularCollatz(num: number): number | void {
    const resto = num % 2;
    let resultado = 0;

    if (num !== 0) {
      if (resto === 0) {
        resultado = num / 2;
      } else {
        resultado = num * 3 + 1;
      }

      if (resultado !== 1) {
        this.calcularCollatz(resultado);
        this.resultadoCollatz.push(resultado);
      } else {
        return;
      }
    } else {
      return;
    }
  }

  ngOnInit(): void {
    this.route.paramMap.subscribe((params: ParamMap) => {
      this.resultadoCollatz.splice(0);
      // Parseamos a número
      this.numCollatz = +params.get('num')!;
      this.calcularCollatz(this.numCollatz);
    });
  }
}

<div>
  <ul>
    <li *ngFor="let resultado of resultadoCollatz">
      {{ resultado }}
    </li>
  </ul>
</div>
