// PRACTICAS/examenvueFMB/src/components/HomeComponent.vue
<template>
    <div class="m-3">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col" v-for="cubo in data.cubos" :key="cubo">
                <div class="card">
                    <div class="card-body ,-3">
                        <img width="100" :src="cubo.imagen" alt="" />
                        <h5 class="card-title">{{ cubo.modelo }}</h5>
                        <p class="card-text">{{ cubo.precio }}</p>
                        <router-link
                            class="card-text btn btn-primary"
                            :to="'/cubos-detalles/' + cubo.idCubo"
                            routerLinkActive="router-link-active"
                        >
                            Detalles
                        </router-link>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { reactive, onMounted } from "vue";
import cubosService from "@/services/cubosService";

const data = reactive({
    cubos: [],
});

onMounted(() => {
    cubosService.getCubos().then((res) => {
        data.cubos = res.data;
    });
});
</script>

// PRACTICAS/examenangularFMB/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Cubo } from 'src/app/models/cubo';
import { CubosServiceService } from 'src/app/services/cubos-service.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  public cubos!: Cubo[];

  constructor(private cubosService: CubosServiceService) {}

  ngOnInit(): void {
    this.cubosService.getCubos().subscribe((res) => {
      this.cubos = res;
    });
  }
}

<div class="m-3">
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col" *ngFor="let cubo of cubos">
      <div class="card">
        <div class="card-body ,-3">
          <img width="100" src="{{ cubo.imagen }}" alt="" />
          <h5 class="card-title">{{ cubo.modelo }}</h5>
          <p class="card-text">{{ cubo.precio }}</p>
          <router-link
            class="card-text btn btn-primary"
            [routerLink]="['/cubos-detalles', cubo.idCubo]"
            routerLinkActive="router-link-active"
            routerLinkActive="router-link-active"
          >
            Detalles
          </router-link>
        </div>
      </div>
    </div>
  </div>
</div>
