// vue/vueseries/src/components/MenuComponent.vue
<template>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <router-link
                            class="nav-link"
                            aria-current="page"
                            to="/"
                        >
                            <img
                                src="../assets/images/menu-icon.png"
                                width="75"
                                alt="Home icon"
                            />
                        </router-link>
                    </li>
                    <li class="nav-item">
                        <router-link
                            class="nav-link"
                            aria-current="page"
                            to="/nuevo-personaje"
                        >
                            Nuevo personaje
                        </router-link>
                    </li>
                    <li class="nav-item">
                        <router-link
                            class="nav-link"
                            aria-current="page"
                            to="/modificar-personajes"
                        >
                            Modificar personajes
                        </router-link>
                    </li>
                    <li class="nav-item dropdown">
                        <router-link
                            class="nav-link dropdown-toggle"
                            to="#"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                        >
                            Series
                        </router-link>
                        <ul class="dropdown-menu">
                            <li v-for="serie in series" :key="serie.idSerie">
                                <router-link
                                    class="dropdown-item"
                                    :to="`/serie/${serie.idSerie}`"
                                >
                                    {{ serie.nombre }}
                                </router-link>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<script setup>
import { inject, onMounted, reactive } from "vue";

const { series } = inject("series");

const data = reactive({
    series: [],
});

onMounted(() => {
    data.series = series;
});
</script>

// react/reactchampions/src/components/Menu.jsx
import React, { Component } from "react";
import MenuEquipos from "./MenuEquipos";
import { Outlet, Link } from "react-router-dom";
import championsIcon from "../assets/images/champions-icon.png";

export default class Menu extends Component {
    render() {
        return (
            <div>
                <nav className="navbar navbar-expand-lg bg-light">
                    <div className="container-fluid">
                        <Link className="navbar-brand" to="/">
                            <img
                                width={50}
                                src={championsIcon}
                                alt="Champions"
                            />
                        </Link>
                        <button
                            className="navbar-toggler"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle navigation"
                        >
                            <span className="navbar-toggler-icon"></span>
                        </button>
                        <div
                            className="collapse navbar-collapse"
                            id="navbarSupportedContent"
                        >
                            <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                                <li className="nav-item">
                                    <Link className="nav-link" to={"/"}>
                                        Home
                                    </Link>
                                </li>
                                <li className="nav-item">
                                    <Link className="nav-link" to={"/apuestas"}>
                                        Apuestas
                                    </Link>
                                </li>
                                <MenuEquipos equipos={this.props.equipos} />
                            </ul>
                        </div>
                    </div>
                </nav>

                <Outlet />
            </div>
        );
    }
}
