// react/reactrutasforms/src/components/Cine.jsx
import React, { Component } from "react";
import cineImage from "../assets/images/cine.jpg";

export default class Cine extends Component {
    render() {
        return (
            <div>
                <h1 className="App-header">Cine</h1>
                <img src={cineImage} alt="Cine" />
            </div>
        );
    }
}

// angular/rutasangular/src/app/components/cine/cine.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cine',
  templateUrl: './cine.component.html',
  styleUrls: ['./cine.component.css'],
})
export class CineComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div>
  <p>cine works!</p>
  <img src="../../../assets/images/cine.jpg" alt="" />
</div>
