// PRACTICAS/examenvueFMB/src/components/LoginComponent.vue
<template>
    <form class="m-5" @submit.prevent="login">
        <label>Usuario</label>
        <input
            type="text"
            class="form-control"
            name="cajaUsuario"
            required
            v-model="data.email"
        /><br />
        <label>Contraseña</label>
        <input
            type="password"
            class="form-control"
            name="cajaPass"
            v-model="data.pass"
            required
        /><br />
        <button type="submit" class="btn btn-info">Login</button>
    </form>
</template>

<script setup>
import { reactive, onMounted } from "vue";
import { useRouter } from "vue-router";
import authService from "@/services/authService";

const router = useRouter();

const data = reactive({
    email: "",
    pass: "",
});

const login = () => {
    if (data.email && data.pass) {
        const loginUser = {
            email: data.email,
            password: data.pass,
        };

        authService.login(loginUser);
        router.push("/perfil");
    }
};

onMounted(() => {
    authService.checkUser().then((user) => {
        if (user) {
            router.push("/perfil");
        } else {
            router.push("/login");
        }
    });
});
</script>

// PRACTICAS/examenangularFMB/src/app/components/login/login.component.ts
// Base
import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';
// Model
// Models
import { User } from 'src/app/models/user';
// Service
import { AuthServiceService } from 'src/app/services/auth-service.service';
import { CubosServiceService } from 'src/app/services/cubos-service.service';
// Rutas
import { ActivatedRoute, ParamMap, Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  // Form inputs
  @ViewChild('cajaUsuario') cajaUsuario!: ElementRef;
  @ViewChild('cajaPass') cajaPass!: ElementRef;

  constructor(
    private cubosService: CubosServiceService,
    private authService: AuthServiceService,
    private router: Router
  ) {}

  login(): void {
    const user = this.cajaUsuario.nativeElement.value;
    const pass = this.cajaPass.nativeElement.value;

    if (user && pass) {
      const loginUser = {
        email: user,
        password: pass,
      };

      this.authService.login(loginUser);
    }
  }

  ngOnInit(): void {
    this.authService.checkUser().then((user) => {
      if (user) {
        this.router.navigate(['/perfil']);
      } else {
        this.router.navigate(['/login']);
      }
    });
  }
}

<form class="m-5">
  <label>Usuario</label>
  <input
    type="text"
    class="form-control"
    name="cajaUsuario"
    required
    #cajaUsuario
  /><br />
  <label>Contraseña</label>
  <input
    type="password"
    class="form-control"
    name="cajaPass"
    #cajaPass
    required
  /><br />
  <button type="submit" class="btn btn-info" (click)="login()">Login</button>
</form>
