// react/reactclases/src/components/HijoNumero.jsx
import React, { Component } from "react";

export default class HijoNumero extends Component {
    render() {
        return (
            <div>
                <h1>Número hijo: {this.props.valor}</h1>
                <button
                    onClick={() => {
                        this.props.sumarNumero(this.props.valor);
                    }}
                >
                    Sumar {this.props.valor}
                </button>
            </div>
        );
    }
}

// vue/vuepadrehijo/src/components/numeros/HijoNumero.vue
<template>
    <div>
        <h1>Hijo Numero</h1>
        <h3>Valor: {{ valor }}</h3>
        <button @click="enviarValor">Sumar</button>
    </div>
</template>

<script>
export default {
    props: {
        valor: Number,
    },
    methods: {
        enviarValor() {
            this.$emit("response", this.valor);
        },
    },
};
</script>
