// PRACTICAS/examenvueFMB/src/components/PerfilComponent.vue
<template>
    <div
        v-if="data.perfil"
        style="display: flex; justify-content: center"
        class="mt-5"
    >
        <div class="card" style="width: 18rem">
            <div class="card-body">
                <h5 class="card-title">Estás loggeado</h5>
                <p class="card-text">Email: {{ data.perfil.email }}</p>
                <p class="card-text">Nombre: {{ data.perfil.nombre }}</p>
            </div>
        </div>
    </div>
</template>

<script setup>
import { reactive, onMounted } from "vue";
import cubosService from "@/services/cubosService";
import authService from "@/services/authService";
import { useRouter } from "vue-router";

const router = useRouter();

const data = reactive({
    perfil: {},
});

/**
 * Carga el perfil del usuario del servidor.
 */
const loadPerfil = async () => {
    /*
      LLamamos al metodo auth para recoger la funcion copia provista del header.
      Para no perder el contexto de la peticion original, le damos el contexto del service al que pertenece.
    */
    const validatedCall = await authService.authInterceptor(
        cubosService.getPerfilUsuario.bind(cubosService)
    );

    /*
      La funcion copia de auth es la misma que una peticion http.
      Si hay un código existente en localStorage, pero no es válido, devolverá un error 401 y se reseteara el token.
    */
    validatedCall().then(
        (res) => {
            data.perfil = res.data;
        },
        (err) => {
            if (err.status == 401) {
                authService.logout();
            }
        }
    );
};

onMounted(() => {
    authService.checkUser().then((user) => {
        if (!user) {
            router.push("/login");
        }
    });
    loadPerfil();
});
</script>

<style></style>

// PRACTICAS/examenangularFMB/src/app/components/perfil/perfil.component.ts
// Angular
import { Component, OnInit } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
// Services
import { AuthServiceService } from 'src/app/services/auth-service.service';
import { CubosServiceService } from 'src/app/services/cubos-service.service';
// Models
import { User } from 'src/app/models/user';

@Component({
  selector: 'app-perfil',
  templateUrl: './perfil.component.html',
  styleUrls: ['./perfil.component.css'],
})
export class PerfilComponent implements OnInit {
  public perfil!: User;

  constructor(
    private authService: AuthServiceService,
    private cubosService: CubosServiceService
  ) {}

  /**
   * Carga el perfil del usuario del servidor.
   */
  async loadPerfil(): Promise<void> {
    /*
      LLamamos al metodo auth para recoger la funcion copia provista del header.
      Para no perder el contexto de la peticion original, le damos el contexto del service al que pertenece.
    */
    const validatedCall = await this.authService.authInterceptor(
      this.cubosService.getPerfilUsuario.bind(this.cubosService)
    );

    /*
      La funcion copia de auth es la misma que una peticion http.
      Si hay un código existente en localStorage, pero no es válido, devolverá un error 401 y se reseteara el token.
    */
    validatedCall().subscribe(
      (res: User) => {
        this.perfil = res;
      },
      (err: HttpErrorResponse) => {
        if (err.status == 401) {
          this.authService.logout();
        }
      }
    );
  }

  ngOnInit(): void {
    this.loadPerfil();
  }
}

<div *ngIf="perfil" style="display: flex; justify-content: center" class="mt-5">
  <div class="card" style="width: 18rem">
    <div class="card-body">
      <h5 class="card-title">Estás loggeado</h5>
      <p class="card-text">Email: {{ perfil.email }}</p>
      <p class="card-text">Nombre: {{ perfil.nombre }}</p>
    </div>
  </div>
</div>
