// PRACTICAS/examenvueFMB/src/components/MenuComponent.vue
<template>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <router-link
                class="navbar-brand"
                to="/"
                routerLinkActive="router-link-active"
            >
                <img width="100" src="../assets/images/home-icon.png" alt="" />
            </router-link>
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a
                            class="nav-link dropdown-toggle"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                        >
                            Marcas
                        </a>
                        <ul class="dropdown-menu">
                            <li v-for="marca in data.marcas" :key="marca">
                                <router-link
                                    :to="'/cubos-marca/' + marca"
                                    class="dropdown-item"
                                >
                                    {{ marca }}
                                </router-link>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a
                            class="nav-link dropdown-toggle"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                        >
                            Modelos
                        </a>
                        <ul class="dropdown-menu">
                            <li v-for="cubo in data.cubos" :key="cubo">
                                <router-link
                                    class="dropdown-item"
                                    :to="'/cubos-detalles/' + cubo.idCubo"
                                >
                                    {{ cubo.modelo }}
                                </router-link>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <router-link class="nav-link" to="/compras-usuario">
                            Ver tus compras
                        </router-link>
                    </li>
                    <li class="nav-item">
                        <router-link class="nav-link" to="/login">
                            Login
                        </router-link>
                    </li>
                    <li class="nav-item">
                        <router-link class="nav-link" to="/register">
                            Register
                        </router-link>
                    </li>
                    <li class="nav-item">
                        <a
                            style="cursor: pointer"
                            class="nav-link"
                            @click="logout"
                        >
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<script setup>
import cubosService from "@/services/cubosService";
import authService from "@/services/authService";
import { onMounted, reactive } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();

const data = reactive({
    marcas: [],
    cubos: [],
});

const logout = () => {
    authService.logout();
    router.push("/");
};

onMounted(() => {
    cubosService.getMarcas().then((res) => (data.marcas = res.data));
    cubosService.getCubos().then((res) => (data.cubos = res.data));
});
</script>

// PRACTICAS/examenangularFMB/src/app/components/menu/menu.component.ts
// Base
import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';
// Models
import { Marca } from 'src/app/models/marca';
import { Cubo } from 'src/app/models/cubo';
// Service
import { CubosServiceService } from 'src/app/services/cubos-service.service';
import { AuthServiceService } from 'src/app/services/auth-service.service';
// Rutas
import { ActivatedRoute, ParamMap, Router } from '@angular/router';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css'],
})
export class MenuComponent implements OnInit {
  public marcas!: Marca[];
  public cubos!: Cubo[];

  constructor(
    private cubosService: CubosServiceService,
    private authService: AuthServiceService
  ) {}

  logout(): void {
    this.authService.logout();
  }

  ngOnInit(): void {
    this.cubosService.getMarcas().subscribe((res) => (this.marcas = res));
    this.cubosService.getCubos().subscribe((res) => (this.cubos = res));
  }
}

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a
      class="navbar-brand"
      [routerLink]="['/']"
      routerLinkActive="router-link-active"
    >
      <img width="100" src="../../../assets/images/home-icon.png" alt="" />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Marcas
          </a>
          <ul class="dropdown-menu">
            <li *ngFor="let marca of marcas">
              <a
                class="dropdown-item"
                [routerLink]="['cubos-marca', marca]"
                routerLinkActive="router-link-active"
              >
                {{ marca }}
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Modelos
          </a>
          <ul class="dropdown-menu">
            <li *ngFor="let cubo of cubos">
              <a
                class="dropdown-item"
                [routerLink]="['cubos-detalles', cubo.idCubo]"
                routerLinkActive="router-link-active"
              >
                {{ cubo.modelo }}
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/compras-usuario']"
            routerLinkActive="router-link-active"
          >
            Ver tus compras
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/login']"
            routerLinkActive="router-link-active"
          >
            Login
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/register']"
            routerLinkActive="router-link-active"
          >
            Register
          </a>
        </li>
        <li class="nav-item">
          <a
            style="cursor: pointer"
            class="nav-link"
            (click)="logout()"
            routerLinkActive="router-link-active"
          >
            Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
