// vue/vueseries/src/components/MenuComponent.vue
<template>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <router-link
                            class="nav-link"
                            aria-current="page"
                            to="/"
                        >
                            <img
                                src="../assets/images/menu-icon.png"
                                width="75"
                                alt="Home icon"
                            />
                        </router-link>
                    </li>
                    <li class="nav-item">
                        <router-link
                            class="nav-link"
                            aria-current="page"
                            to="/nuevo-personaje"
                        >
                            Nuevo personaje
                        </router-link>
                    </li>
                    <li class="nav-item">
                        <router-link
                            class="nav-link"
                            aria-current="page"
                            to="/modificar-personajes"
                        >
                            Modificar personajes
                        </router-link>
                    </li>
                    <li class="nav-item dropdown">
                        <router-link
                            class="nav-link dropdown-toggle"
                            to="#"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                        >
                            Series
                        </router-link>
                        <ul class="dropdown-menu">
                            <li v-for="serie in series" :key="serie.idSerie">
                                <router-link
                                    class="dropdown-item"
                                    :to="`/serie/${serie.idSerie}`"
                                >
                                    {{ serie.nombre }}
                                </router-link>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<script setup>
import { inject, onMounted, reactive } from "vue";

const { series } = inject("series");

const data = reactive({
    series: [],
});

onMounted(() => {
    data.series = series;
});
</script>

// angular/practicaexamen/src/app/components/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Serie } from 'src/app/models/serie';
import { SeriesService } from 'src/app/services/series.service';
import { Plantilla } from 'src/app/models/plantilla';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css'],
})
export class MenuComponent implements OnInit {
  public series!: Serie[];
  public user!: any;

  constructor(
    private seriesService: SeriesService,
    private authService: AuthService
  ) {}

  loadSeries(): void {
    this.seriesService.getSeries().subscribe((res) => (this.series = res));
  }

  logout(): void {
    this.authService.logout();
    this.authService.checkUser().then((user) => {
      if (user) this.user = user;
    });
  }

  ngOnInit(): void {
    this.loadSeries();
    this.authService.checkUser().then((user) => {
      if (user) this.user = user;
    });
  }
}

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a
      class="navbar-brand"
      [routerLink]="['/']"
      routerLinkActive="router-link-active"
    >
      HOME
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/nuevo-personaje']"
            routerLinkActive="router-link-active"
          >
            Nuevo Personaje
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/modificar-personaje']"
            routerLinkActive="router-link-active"
          >
            Modificar Personaje
          </a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Series
          </a>
          <ul class="dropdown-menu">
            <li *ngFor="let serie of series">
              <a
                class="dropdown-item"
                [routerLink]="['/detalles-serie/', serie.idSerie]"
                routerLinkActive="router-link-active"
              >
                {{ serie.nombre }}
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/plantilla']"
            routerLinkActive="router-link-active"
          >
            Plantilla
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/subordinados']"
            routerLinkActive="router-link-active"
          >
            Subordinados
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/perfil-empleado']"
            routerLinkActive="router-link-active"
          >
            Perfil {{ user.userName }}
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            [routerLink]="['/perfil-empleado']"
            routerLinkActive="router-link-active"
            (click)="logout()"
          >
            Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
