// PRACTICAS/examenvueFMB/src/components/CubosMarca.vue
<template>
    <div>
        <h1 v-if="data.marca">Cubos de la marca: {{ data.marca }}</h1>
        <div class="card-group">
            <div class="card" v-for="cubo in data.cubos" :key="cubo">
                <img
                    width="300"
                    :src="cubo.imagen"
                    class="card-img-top"
                    alt=""
                />
                <div class="card-body">
                    <h5 class="card-title">{{ cubo.modelo }}</h5>
                    <p class="card-text">{{ cubo.precio }}</p>
                    <router-link
                        class="card-text btn btn-primary"
                        :to="'/cubos-detalles/' + cubo.idCubo"
                        routerLinkActive="router-link-active"
                    >
                        Detalles
                    </router-link>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { reactive, onMounted } from "vue";
import { useRoute } from "vue-router";
import cubosService from "@/services/cubosService";

const data = reactive({
    marca: "",
    cubos: [],
});

const route = useRoute();

onMounted(() => {
    const marca = route.params.marca;

    data.marca = marca;

    cubosService.getCubosMarca(marca).then((res) => {
        data.cubos = res.data;
    });
});
</script>

// PRACTICAS/examenangularFMB/src/app/components/cubos-marca/cubos-marca.component.ts
// Base
import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';
// Models
import { Cubo } from 'src/app/models/cubo';
// Service
import { CubosServiceService } from 'src/app/services/cubos-service.service';
// Rutas
import { ActivatedRoute, ParamMap, Router } from '@angular/router';

@Component({
  selector: 'app-cubos-marca',
  templateUrl: './cubos-marca.component.html',
  styleUrls: ['./cubos-marca.component.css'],
})
export class CubosMarcaComponent implements OnInit {
  public cubos!: Cubo[];
  public marca!: string;

  constructor(
    private cubosService: CubosServiceService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  redirect(num: number) {
    this.router.navigate(['numerodoble', num]);
  }

  ngOnInit(): void {
    this.route.paramMap.subscribe((params: ParamMap) => {
      const marca = params.get('marca')!;
      this.marca = marca;
      this.cubosService.getCubosMarca(marca).subscribe((res) => {
        this.cubos = res;
      });
    });
  }
}

<h1 *ngIf="marca">Cubos de la marca: {{ marca }}</h1>
<div class="card-group">
  <div class="card" *ngFor="let cubo of cubos">
    <img width="300" src="{{ cubo.imagen }}" class="card-img-top" alt="" />
    <div class="card-body">
      <h5 class="card-title">{{ cubo.modelo }}</h5>
      <p class="card-text">{{ cubo.precio }}</p>
      <p
        class="card-text btn btn-primary"
        [routerLink]="['/cubos-detalles', cubo.idCubo]"
        routerLinkActive="router-link-active"
      >
        Detalles
      </p>
    </div>
  </div>
</div>
